// <auto-generated />
using System;
using DarlingDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace VManager.Migrations
{
    [DbContext(typeof(Db))]
    partial class DbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("VManager.db.Model.Dates", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date_Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Important")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("VtuberId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VtuberId");

                    b.ToTable("Dates");
                });

            modelBuilder.Entity("VManager.db.Model.Generate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("img")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Generate");
                });

            modelBuilder.Entity("VManager.db.Model.Vtuber", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("Kicked")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("LastSubs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TwitchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vtuber");

                    b.HasData(
                        new
                        {
                            Id = 1ul,
                            Color = "c8738b",
                            Image = new byte[0],
                            Kicked = false,
                            LastSubs = 0ul,
                            Name = "KraNf",
                            TelegramId = 493373972L,
                            TwitchId = 808276081ul
                        },
                        new
                        {
                            Id = 2ul,
                            Color = "cb2b72",
                            Image = new byte[0],
                            Kicked = false,
                            LastSubs = 0ul,
                            Name = "Tsunya",
                            TelegramId = 545498845L,
                            TwitchId = 118662043ul
                        },
                        new
                        {
                            Id = 3ul,
                            Color = "ad77ca",
                            Image = new byte[0],
                            Kicked = false,
                            LastSubs = 0ul,
                            Name = "Pewa",
                            TelegramId = 532671775L,
                            TwitchId = 827228470ul
                        },
                        new
                        {
                            Id = 4ul,
                            Color = "b4323d",
                            Image = new byte[0],
                            Kicked = false,
                            LastSubs = 0ul,
                            Name = "Aya",
                            TelegramId = 930000855L,
                            TwitchId = 547036080ul
                        },
                        new
                        {
                            Id = 5ul,
                            Color = "e8bd5e",
                            Image = new byte[0],
                            Kicked = false,
                            LastSubs = 0ul,
                            Name = "xXxpososu",
                            TelegramId = 818767715L,
                            TwitchId = 820065100ul
                        });
                });

            modelBuilder.Entity("VManager.db.Model.Dates", b =>
                {
                    b.HasOne("VManager.db.Model.Vtuber", "Vtuber")
                        .WithMany("Dates")
                        .HasForeignKey("VtuberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vtuber");
                });

            modelBuilder.Entity("VManager.db.Model.Vtuber", b =>
                {
                    b.Navigation("Dates");
                });
#pragma warning restore 612, 618
        }
    }
}
